[package]
name = "ytm"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", features = ["json", "gzip", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1"

