name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Set version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "Setting Cargo.toml version to $VERSION"
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml

      - name: Commit version bump
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Cargo.toml
          git commit -m "Bump version to $VERSION from tag" || echo "No changes to commit"
          git push

  build-arm64:
    runs-on: macos-14
    needs: bump-version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
    
      - uses: dtolnay/rust-toolchain@stable
      - name: Build ARM64 binary
        run: |
          cargo build --release
          tar -czvf ytm-macos-arm64.tar.gz -C target/release ytm
      - name: Upload ARM64 binary
        uses: softprops/action-gh-release@v2
        with:
          files: ytm-macos-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-x86_64:
    runs-on: macos-13
    needs: bump-version
    steps:
      - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
          
      - uses: dtolnay/rust-toolchain@stable
      - name: Build x86_64 binary
        run: |
          cargo build --release
          tar -czvf ytm-macos-x86_64.tar.gz -C target/release ytm
      - name: Upload x86_64 binary
        uses: softprops/action-gh-release@v2
        with:
          files: ytm-macos-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-formula:
    runs-on: ubuntu-latest
    needs: [build-arm64, build-x86_64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Download release assets
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          fileName: "ytm-macos-*.tar.gz"

      - name: Calculate checksums
        id: shasum
        run: |
          ARM_SHA=$(shasum -a 256 ytm-macos-arm64.tar.gz | awk '{print $1}')
          INTEL_SHA=$(shasum -a 256 ytm-macos-x86_64.tar.gz | awk '{print $1}')
          echo "arm=$ARM_SHA" >> $GITHUB_OUTPUT
          echo "intel=$INTEL_SHA" >> $GITHUB_OUTPUT

      - name: Update formula
        run: |
          VERSION=${GITHUB_REF_NAME#v}

          sed -i "s/^  version \".*\"/  version \"${VERSION}\"/" Formula/ytm.rb

          sed -i "s|/releases/download/v[^/]\+/ytm-macos-arm64.tar.gz|/releases/download/v${VERSION}/ytm-macos-arm64.tar.gz|" Formula/ytm.rb
          sed -i "s|/releases/download/v[^/]\+/ytm-macos-x86_64.tar.gz|/releases/download/v${VERSION}/ytm-macos-x86_64.tar.gz|" Formula/ytm.rb

          sed -i "/ytm-macos-arm64.tar.gz/{n;s/sha256 \".*\"/sha256 \"${{ steps.shasum.outputs.arm }}\"/}" Formula/ytm.rb
          sed -i "/ytm-macos-x86_64.tar.gz/{n;s/sha256 \".*\"/sha256 \"${{ steps.shasum.outputs.intel }}\"/}" Formula/ytm.rb

      - name: Commit formula update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Formula/ytm.rb
          git commit -m "Update Homebrew formula for ${{ github.ref_name }}" || echo "No changes to commit"
          git push
