name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, x86_64]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: |
          cargo build --release
          tar -czvf ytm-macos-${{ matrix.arch }}.tar.gz -C target/release ytm

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: ytm-macos-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-formula:
    runs-on: ubuntu-latest
    needs: build-macos
    steps:
      - uses: actions/checkout@v4

      - name: Download release assets
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          fileName: "ytm-macos-*.tar.gz"

      - name: Calculate checksums
        id: shasum
        run: |
          ARM_SHA=$(shasum -a 256 ytm-macos-arm64.tar.gz | awk '{print $1}')
          INTEL_SHA=$(shasum -a 256 ytm-macos-x86_64.tar.gz | awk '{print $1}')
          echo "arm=$ARM_SHA" >> $GITHUB_OUTPUT
          echo "intel=$INTEL_SHA" >> $GITHUB_OUTPUT

      - name: Update formula
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          sed -i "s/version \".*\"/version \"${VERSION}\"/" Formula/ytm.rb
          sed -i "s|ytm-macos-arm64.tar.gz\".*|ytm-macos-arm64.tar.gz\"\\n      sha256 \"${{ steps.shasum.outputs.arm }}\"|" Formula/ytm.rb
          sed -i "s|ytm-macos-x86_64.tar.gz\".*|ytm-macos-x86_64.tar.gz\"\\n      sha256 \"${{ steps.shasum.outputs.intel }}\"|" Formula/ytm.rb

      - name: Commit formula update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Formula/ytm.rb
          git commit -m "Update Homebrew formula for ${{ github.ref_name }}"
          git push
